# Site wide configuration

title: The Icarus Project NYC
description: "Website for The Icarus Project NYC, a mental health grassroots organization commited to advocacy, community, and the creative arts."
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //test388.github.io/reference

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: NYC Icarus
  web: http://icarusnyc.com
  email: nycicarus@gmail.com
  twitter: mmistakes
  bio: "The Icarus Project NYC is a mental health grassroots organization commited to advocacy, community, and the creative arts."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +MichaelRoseDesign
    ad-client: 
    ad-slot: 
  disqus-shortname: nycicarus


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
